### ISSUE TITLE
Updating the "user" in tweets

### ISSUE THREAD

**Issue by dwhelan** [parroty/extwitter#100]
Hi,

I noticed that the ExTwitter parser does a custom struct for the "user" element in a tweet:

```elixir
defmodule ExTwitter.Parser do
  def parse_tweet(object) do
    tweet = struct(ExTwitter.Model.Tweet, object)
    user  = parse_user(tweet.user)
    %{tweet | user: user}
  end

 # ...

  def parse_user(object) do
    struct(ExTwitter.Model.User, object)
  end
```

Currently, the user struct seems to be out of sync with the JSON being returned. As a result, there are differences between the JSON encoded ExTwitter.Model.Tweet (left) and the original JSON tweet (right):

<img width="1418" alt="screen shot 2018-05-09 at 1 41 20 pm" src="https://user-images.githubusercontent.com/17627/39830651-12d8e9da-5390-11e8-88ef-a8c9c08d5d15.png">

Specifically, the user element in the tweet is missing the `translator_type` field and has extra fields that are always `null` because they are not present in the incoming tweet:

```
    "status": null,
    "email": null,
    "withheld_scope": null,
    "entities": null,
    "is_translation_enabled": null,
    "withheld_in_countries": null,
    "show_all_inline_media": null,
```
Would it be possible to update the User struct to remove this mismatch? Or perhaps just eliminate the special handling for the "user" element?

Happy to help with this.

**Comment by Mdlkxzmcp** [comment]
If you check the [User Object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object), you will see that `translator_type` is marked as deprecated. Adding a `raw_data` would be nice, so that when such changes happen, the data can still be accessed, even if exTwitter is lagging slightly behind... Making a PR with this stuff atm~
