### ISSUE TITLE
Twitter Streaming API can return multiple portions of tweets in a given chunk

### ISSUE THREAD

**Issue by pjskennedy** [parroty/extwitter#105]
Hey there, I noticed that the twitter streaming API can return two separate portions of tweets in a given message. I was receiving errors using the streaming API due to JSON parse errors. I took a look and saw it was trying to parse two JSON documents concatenated together. 

```
[error] Error returned, stopping stream ({{:invalid, "{", 8142}, "{\"created_at\":\"Sat Oct 13 23:00:18 +0000 2018\"...
```

Twitter's [API Doc's](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data.html):
> note that Tweets and other streamed messages will not necessarily fall on HTTP chunk boundaries – be sure to use the delimiter defined above to determine activity boundaries when reassembling the stream.

I took a shot and getting this to work and it seemed to solve the problem I was facing: https://github.com/parroty/extwitter/pull/104

**Comment by cheerfulstoic** [comment]
This definitely helped me!  I was having to restart my stream multiple times, but now it's running smoothly.  It would be great if this was released as part of the official `extwitter` package!

**Comment by pjskennedy** [comment]
@parroty Curious if this can get a lookover?

**Comment by pjskennedy** [comment]
Fixed in https://github.com/parroty/extwitter/commit/7a87f098b116a4ea72ce0481fc7a4a0906cc92bb

**Comment by parroty** [comment]
Thank you for updating the item, and sorry about the slow responses.
