### ISSUE TITLE
Calling ExTwitter.stream_xxx and stream operations (ex. Stream.take) in different processes fails to receive tweets

### ISSUE THREAD

**Issue by parroty** [parroty/extwitter#12]

**Comment by parroty** [comment]
Need investigate feasibility as current implementation directly depends on message passing between pids. Current interface of stream is just a data stream without control mechanism, and it might need different set of interface.

**Comment by parroty** [comment]
It's caused by the structure to create stream using process message box, then I was experimenting on callback approach instead of stream. It seems to work, but not sure if it's worthwhile to implement 2 different syntaxes.

```elixir
ExTwitter.stream_sample(receive_messages: true, fn(tweet) -> 
  IO.inspect tweet)
end)
```

**Comment by X4lldux** [comment]
My proposition should fix this. Allows to create the stream in a different process then the consumer will be, by lazy initiating `AsyncRequest` - or actually, finalization of initialization, by setting `processor` field in first fn of `Stream.resource` while the rest of records is set where it orignally was.

**Comment by parroty** [comment]
Thanks, I'll try to check the behavior over the weekend. 
Current tests for streams are a little tricky and might need to tweak too.

**Comment by parroty** [comment]
Closing with #19.
