### ISSUE TITLE
Replace Poison with Jason

### ISSUE THREAD

**Issue by praveenperera** [parroty/extwitter#121]
Since Jason is faster than Poison and seems to be the go to library for working with JSON in elixir and phoenix should we replace Poison with Jason.

This would mean one less dependency in most projects (since Phoenix comes default with Jason). And Jason seems to be faster the more active library as well.

We could also make the JSON library configurable but default to Jason. 

I could make this change.

**Comment by cgorshing** [comment]
I believe this can be closed now that the above PR has been merged.

**Comment by praveenperera** [comment]
Awesome! Thanks
