### ISSUE TITLE
Support OAuth authorization flow

### ISSUE THREAD

**Issue by arjan** [parroty/extwitter#14]
It would be handy when this library could also support the OAuth dance. I'm thinking along the lines of this:

 - `ExTwitter.API.Authorize.request_token/0` -- calls Twitter to get a request token
 - `ExTwitter.API.Authorize.authorize_url/2` (with `oauth_token` and `redirect_url` parameters) -- returns a url to which the user should be redirected; this is the Twitter logon / authorize page.
 - `ExTwitter.API.Authorize.access_token/3` (with `verifier`, `request_token`, `request_secret` parameters) -- Verify that the request token was authorized and swap it for an access token.

**Comment by arjan** [comment]
I've started working on this.

**Comment by parroty** [comment]
Thank you for the feedback. Is this about the following methods?
- https://dev.twitter.com/oauth/reference/post/oauth/access_token
- https://dev.twitter.com/oauth/reference/post/oauth/request_token

This page seems to talk about both oauth1.0 and oauth2.0, and I'm having some difficulties to understand how it should work. Ruby's twitter gem seems to implement oauth2.0 token retrieval, but it seems a little different method set.
- https://github.com/sferik/twitter/blob/master/lib/twitter/rest/oauth.rb

I'll be checking more later, but if you have any more insight, it helps a lot.

**Comment by arjan** [comment]
Yes, those 2 calls.

**Comment by arjan** [comment]
Check my implementation here:
https://github.com/arjan/extwitter/blob/oauth-authorize/lib/extwitter/api/authorize.ex

(notice that that branch also contains some other commits, I'll clean it up before I do a PR)

**Comment by parroty** [comment]
Thanks, it sounds nice. Can I get example usage in your app (or tests)? I would like to try out too, and maybe good to expose them to top (ExTwitter) module.

**Comment by arjan** [comment]
Yes exposing would be nice. Test cases are difficult as authorization requires user interaction.
But I'll provide an example controller, so you can see how it is used in Phoenix.

**Comment by parroty** [comment]
Understood. The example controller would help instead.

**Comment by optikfluffel** [comment]
Hey :)
What's the status on that? Would be really helpful to have this in here.

**Comment by arjan** [comment]
https://gist.github.com/arjan/21a501167133cbb38454

**Comment by optikfluffel** [comment]
@arjan cool, will you create a PR for this at some point?

**Comment by omnibs** [comment]
Since it's been so long... @arjan do you mind if I make the PR? I had to fork @parroty's repo and copy your code to use on a perosnal project

**Comment by arjan** [comment]
Sure, go ahead.. it's been too busy here for me to fix this :-/

**Comment by parroty** [comment]
I'm closing this item with #21, but if anyone find further issue, please reopen or open another one.
