### ISSUE TITLE
Could you release new version with JSON changes? <3

### ISSUE THREAD

**Issue by Chipairon** [parroty/extwitter#15]
Hello,

I am using this project to learn about elixir.
Right now I am fetching the master branch due to problems in JSON with 0.3.0 solved in master.

Would be lovely to have a version fixed, just in case :+1: 

Thanks

**Comment by parroty** [comment]
Thanks for the follow ups, I've pushed the master code as v0.4.0 (changing minor version as there're some dependency changes).
