### ISSUE TITLE
configuration key doesn't match application name

### ISSUE THREAD

**Issue by knewter** [parroty/extwitter#26]
First off, let me say - I love this library :)  But I have an issue... (I think just a warning in newer Elixir?)

This is related to the elixir_friends application.  I'm on Elixir 1.1.1 at present, and I get the following error when starting up on the latest extwitter:

```
You have configured application :ex_twitter in your config/config.exs
but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :ex_twitter exists or remove the configuration.
```

This is because the application is named `:extwitter` but the configuration key being used is `:ex_twitter`.  I suppose the fix is to change it to use the key `:extwitter` for the configuration.  I don't believe it's presently breaking anything, but I figured it was worth noting.  I'd be glad to send a PR to fix this if you'd like.

Thanks again!

**Comment by parroty** [comment]
Thanks for the report. I love your screencast :). 
I think it's related to https://github.com/parroty/extwitter/pull/25. The above fix makes sense? (I don't want to break existing code and trying to keep the existing `ex_twitter` for reading part). For the README part, I'll be merging #25.

**Comment by knewter** [comment]
That definitely fixes it.  This isn't sufficient in the current release
though, because you check for ex_twitter when finding config values:
https://github.com/parroty/extwitter/blob/master/lib/extwitter/config.ex#L10

You need to really make those changes...you could check for either value
and offer a deprecation warning in the event that you find people using the
`ex_twitter` configuration name, since that's not really the right
configuration name.  If you merge this PR then following your README won't
actually work at present.

On Wed, Oct 21, 2015 at 8:05 AM, parroty <notifications@github.com> wrote:

> Thanks for the report. I love your screencast :).
> I think it's related to #25 <https://github.com/parroty/extwitter/pull/25>.
> The above fix makes sense? (I don't want to break existing code and trying
> to keep the existing ex_twitter for reading part). For the README part,
> I'll be merging #25 <https://github.com/parroty/extwitter/pull/25>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parroty/extwitter/issues/26#issuecomment-149888106>.
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by parroty** [comment]
> This isn't sufficient in the current release though, because you check for ex_twitter when finding config values:

Could you explain a little more this point? I was assuming `Application.get_env(:extwitter, :oauth, nil) || Application.get_env(:ex_twitter, :oauth, nil)` in https://github.com/parroty/extwitter/commit/07731534465cfdb280abe3e4ac4470346e82682c will pick either of the value (prioritize `extwitter`, but will pick existing `ex_twitter` too). 

Putting warning message (like following?) might be an option, but it may be too much, as elixir is already emitting warning as you indicated in the original comment.

```elixir
defmodule ExTwitter do
  @moduledoc """
  Provides access interfaces for the Twitter API.
  """

  use Application

  @doc false
  def start(_type, _args) do
    if Application.get_env(:ex_twitter, :oauth, nil) do
      IO.puts :stderr, "[deprecation] Using :ex_twitter in config.exs is deprecated. Use :extwitter instead."
    end
    ExTwitter.Supervisor.start_link
  end
```

**Comment by knewter** [comment]
I...completely missed that commit.  I'm sorry!  But maybe the deprecation
would also help people understand how to fix it and that extwitter will
Just Work with the change?

On Wed, Oct 21, 2015 at 4:30 PM, parroty <notifications@github.com> wrote:

> This isn't sufficient in the current release though, because you check for
> ex_twitter when finding config values:
>
> Could you explain a little more this point? I was assuming Application.get_env(:extwitter,
> :oauth, nil) || Application.get_env(:ex_twitter, :oauth, nil) in 0773153
> <https://github.com/parroty/extwitter/commit/07731534465cfdb280abe3e4ac4470346e82682c>
> will pick either of the value (prioritize extwitter, but will pick
> existing ex_twitter too).
>
> Putting warning message (like following?) might be an option, but it may
> be too much, as elixir is already emitting warning as you indicated in the
> original comment.
>
> defmodule ExTwitter do
>   @moduledoc """  Provides access interfaces for the Twitter API.  """
>
>   use Application
>
>   @doc false
>   def start(_type, _args) do
>     if Application.get_env(:ex_twitter, :oauth, nil) do
>       IO.puts :stderr, "[deprecation] Using :ex_twitter in config.exs is deprecated. Use :extwitter instead."
>     end
>     ExTwitter.Supervisor.start_link
>   end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parroty/extwitter/issues/26#issuecomment-150029641>.
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by parroty** [comment]
Thanks. I'll push with the warning message modification (I don't have my laptop with me right now, and allow some time).

**Comment by parroty** [comment]
Pushed as v0.5.1, thanks!
