### ISSUE TITLE
retweeted_status

### ISSUE THREAD

**Issue by mmport80** [parroty/extwitter#28]
I can see the field coming in, but whatever I do I cannot access it with ExTwitter.

Any pointers?

This library's been great so far - only hiccup until now.

**Comment by parroty** [comment]
Thanks for the report. Some attributes were missing and I've tried to fix as v0.5.2. 
Could you retry with v0.5.2?

I checked with the following sample.
```elixir
> retweet = List.first(ExTwitter.retweets(659525458095009792, count: 1))
> retweet.retweeted_status.text
```

**Comment by mmport80** [comment]
Oh nice - just spotted this - will give it a shot asap.

Thx ever so much! : )

**Comment by mmport80** [comment]
Works great - thanks so much again!

**Comment by parroty** [comment]
Thanks!
