### ISSUE TITLE
How to use this package behind a corporate proxy?

### ISSUE THREAD

**Issue by matteoredaelli** [parroty/extwitter#36]
Hello

Where can I configure a proxy server?

Thanks in advance
Matteo
http://www.redaelli.org/matteo/

**Comment by parroty** [comment]
Configuration for proxy server is not available at the moment, but it seems the http client which extwitter is using (erlang-oauth / httpc) has some options to specify proxy. 

Maybe it can be exposed as config setting, though I need some investigations (and trial).

What kind of parameters you would expect? The config settings like the following make sense?

```elxiir
use Mix.Config

config :extwitter, :proxy, [
   server: "www-proxy.mycompany.com",
   port: 8000,
   user: "user",
   password: "password"
]
```

Note: 
- https://github.com/tim/erlang-oauth/
- http://erlang.org/doc/man/httpc.html
- http://erlang.org/doc/apps/inets/http_client.html

**Comment by parroty** [comment]
I just noticed that `erlang-oauth` is not exposing httpc options for `user` and `password` setting, though `server` and `port` can be separately configured. It might need to update erlang-oauth for authentication part (will check some more).

**Comment by parroty** [comment]
I'm making a trial to implement the proxy setting. It would be great if you could try. 

In `config/config.exs`,
```elixir
use Mix.Config

config :extwitter, :proxy, [
   server: "www-proxy.mycompany.com",
   port: 8000,
   user: "user",
   password: "password"
]
```
and in `mix.exs`,
```elixir
defp deps do
  [
    {:oauth, github: "parroty/erlang-oauth", branch: "proxy"},
    {:oauth, github: "parroty/extwitter", branch: "proxy"}
  ]
end
```

**Comment by parroty** [comment]
I've merged to master and closing at the moment (with pending fork of erlang-oauth). If there's remaining issues, please reopen or open another one.

**Comment by matteoredaelli** [comment]
Many thanks
