### ISSUE TITLE
Timex usage

### ISSUE THREAD

**Issue by ASCrookes** [parroty/extwitter#44]
Had a dependency conflict with timex in this package and another one. From the changelog `Drop Timex.Date.now() call in favor of native Erlang (#43).` and grep of the project it doesn't seem like timex is used anymore. Could it be removed if thats the case?

**Comment by ASCrookes** [comment]
Also thanks for this library! Very easy to use

**Comment by parroty** [comment]
Thanks for the comment. The timex is not used on v0.7.0 or later, and I think it can be removed.
