### ISSUE TITLE
Still having "poison" dependency of version ~> 1.5

### ISSUE THREAD

**Issue by tanweerdev** [parroty/extwitter#50]
Please update poison dependency to somewhat ~> 2.0.0. its causing issues with other dependencies in even the release latest version 0.7.1.

**Comment by glennular** [comment]
The code has been fixed and is working in 0.7.2.  It just needs to be pushed to Hex.

You can pull master locally and use that in your deps:

` {:extwitter, path: "../extwitter"} `

fix: b5769779340b9f0c4c3dcac20b8d30ebadfab872

**Comment by cpjolicoeur** [comment]
can we just push the 0.7.2 ?  or when do we anticipate this will be pushed?

**Comment by parroty** [comment]
Thanks for the follow-up. I just pushed the v0.7.2 with dependency updates.
