### ISSUE TITLE
Return {:error, err} tuples instead of throwing errors

### ISSUE THREAD

**Issue by cpjolicoeur** [parroty/extwitter#52]
What was the original design decision to `raise` errors (e.g. in `ExTwitter.Api.Base`) instead of returning an error tuple?  As ExTwitter users we are forced to `try ... rescue` code instead of just pattern matching against a more-standard `{:ok, [...]}` or `{:error, reason}` type return?

Just curious.

**Comment by parroty** [comment]
Thanks for the feedback. In erlang/elixir term, it would be better to use the more-standard one you indicated. It was implemented in the very early phase for simplification of the interface. 
As it's breaking change, I haven't been able to come up with good way or timing for the change. If there's good way of the change, I appreciate suggestions or PRs.

**Comment by cpjolicoeur** [comment]
It definitely is a breaking change, but assuming you are following [semver](http://semver.org/), it's not really a problem as your library hasn't even reached the 1.0 milestone yet.

Making the changes and releasing it as 0.8 or something would be perfectly fine/normal in the semver world, and to me, this kind of change is definitely something that you'd want to have for any kind of 1.0 release.

I'll try to work through it a bit over the next few weeks and see if I can come up with a full PR for the switchover

**Comment by sotojuan** [comment]
Any progress on this?

**Comment by cpjolicoeur** [comment]
Still working on it.  I'm actually down at ElixirConf currently, but haven't finished this up yet.

**Comment by sotojuan** [comment]
No rush, just curious 👍
