### ISSUE TITLE
Replace erlang-oauth with oauther

### ISSUE THREAD

**Issue by tim** [parroty/extwitter#63]
Having a dependency on erlang-oauth creates some confusion and inconvenience for people using this library. For example: https://github.com/tim/erlang-oauth/issues/25 and https://github.com/tim/erlang-oauth/issues/29

Now that Elixir is more established it makes sense to replace erlang-oauth with an Elixir OAuth library such as [oauther](https://github.com/lexmag/oauther). This will make it easier for users of the library to specify their dependencies and make use of extwitter in their projects.

**Comment by parroty** [comment]
Thanks for the comment. I was thinking about this item when proxy was being discussed, but hadn't been able switch. I'll try to revisit.

**Comment by parroty** [comment]
I've updated the dependency as above and will be pushing to hex after completing some other item (thanks for the great library).
