### ISSUE TITLE
Poison errors

### ISSUE THREAD

**Issue by robinsalehjan** [parroty/extwitter#64]
Hi!

I'm getting this error from time to time

```
** (EXIT from #PID<0.177.0>) an exception was raised:
    ** (Poison.SyntaxError) Unexpected end of input
        lib/poison/parser.ex:54: Poison.Parser.parse!/2
        lib/poison.ex:83: Poison.decode!/2
        (extwitter) lib/extwitter/api/base.ex:60: ExTwitter.API.Base.parse_result/1
        (extwitter) lib/extwitter/api/search.ex:10: ExTwitter.API.Search.search/2
        (hashtag_graph) lib/graph/graph.ex:84: HashtagGraph.Graph.tweets/1
        (hashtag_graph) lib/graph/graph.ex:102: HashtagGraph.Graph.get_vertex/1
        (elixir) lib/enum.ex:1233: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1768: Enum."-map/2-anonymous-3-"/3
```

This may be related to #52 

By inspecting my own code, can this error be a case of exceeding the API limit?

Thanks 😄

**Comment by parroty** [comment]
Is there any code or samples that this error can be reproducible?
I assume json response returned from twitter API is incomplete due to some reason. I don't think just hitting API limit cause this error (as long as error response is complete), but may need inspect the condition to identify.

**Comment by robinsjdotcom** [comment]
Not as I know of, it happens from time to time. Will see if I can reproduce it somehow.

The module throwing the error:
https://github.com/robinsjdotcom/TrendingHashtagGraph/blob/dev/apps/hashtag_graph/lib/graph/graph.ex

Functions referenced in the error message:

```  HashtagGraph.Graph.tweets/1
defp tweets(hashtag) do
    response = ExTwitter.search(hashtag, count: 5)           <--- issue
    cond do
      is_list(response) -> {:ok, response}
      is_nil(response) ->  {:error, []}
      true -> {:error, []}
    end
  end
```

``` lib/graph/graph.ex:102
def get_vertex(hashtag) do
    with {:ok, _remaining} <- exceeded_limit?(),
      {:ok, tweets} <- tweets(hashtag),                                                           <--- Issue
      valid_tweets <- Stream.filter(tweets, &(Map.get(&1, :text) != nil)),
      edges <- Enum.map(valid_tweets, &(Map.get(&1, :text)))
    do
      %Vertex{hashtag: hashtag, edges: edges}
    else
      {:error, reason} -> {:error, reason}
      true -> throw RuntimeError.message("Error\n#{System.stacktrace}")
    end
  end
```

**Comment by parroty** [comment]
Thanks for the information. I haven't able to reproduce or find the cause yet.
Based on the `(Poison.SyntaxError) Unexpected end of input` error, I assume incomplete json is passed to Poison. It could be network related issue? (though the data would not be so large with `count: 5`)

If it can be reproduced with some control, debug printing (like setting `IO.inspect(body)` around https://github.com/parroty/extwitter/blob/v0.7.3/lib/extwitter/api/base.ex#L59) could be one option (though it's dirty approach).

> By inspecting my own code, can this error be a case of exceeding the API limit?

I've rechecked this point, but API limit error from Twitter itself is valid json, and it would not be this error.
```
iex(4)> ExTwitter.search("#apple", count: 1)
** (ExTwitter.RateLimitExceededError) Rate limit exceeded
    (extwitter) lib/extwitter/api/base.ex:83: ExTwitter.API.Base.parse_error/2
    (extwitter) lib/extwitter/api/search.ex:10: ExTwitter.API.Search.search/2
```

**Comment by robinsjdotcom** [comment]
Thank you for the answer 😄 

After more trial and error  it's consistently happening at the first API call. I will inspect this in closer detail as soon as I can.

**Comment by robinsjdotcom** [comment]
It successfully parsed every tweet, until this one:

```
{"text":"\\u0627\\u0644\\u0634\\u0628\\u0627\\u0628_\\u0627\\u0644\\u0627\\u0647\\u0644\\u064a","indices":[117,131]}],"symbols":[],"user_mentions":[],"urls":[]},"metadata":{"iso_language_code":"ar","result_type":"recent"},"source":"\\u003ca href=\\"http:\\/\\/twitter.com\\/download\\/iphone\\" rel=\\"nofollow\\"\\u003eTwitter for iPhone\\u003c\\/a\\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":4733960663,"id_str":"4733960663","name":"\\u062a\\u0635\\u0648\\u064a\\u062a\\u0627\\u062a \\u0627\\u0644\\u0639\\u0631\\u0628","screen_name":"Polls4Arabs_","location":"\\u0627\\u0644\\u062e\\u0627\\u0635 \\u0644\\u0644\\u0625\\u0642\\u062a\\u0631\\u0627\\u062d\\u0627\\u062a ","description":"\\u0623\\u0643\\u0628\\u0631 \\u062d\\u0633\\u0627\\u0628 \\u0639\\u0631\\u0628\\u064a \\u0644\\u0644\\u062a\\u0635\\u0648\\u064a\\u062a\\u0627\\u062a | \\u0644\\u0627\\u062a\\u0646\\u0633\\u0649 \\u062a\\u0641\\u0639\\u0651\\u0644 \\u0627\\u0644\\u062a\\u0646\\u0628\\u064a\\u0647\\u0627\\u062a \\ud83d\\udd14","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":187927,"friends_count":43851,"listed_count":37,"created_at":"Thu Jan 07 11:16:39 +0000 2016","favourites_count":10,"utc_offset":-28800,"time_zone":"Pacific Time (US & Canada)","geo_enabled":false,"verified":false,"statuses_count":991,"lang":"en","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"F5F8FA","profile_background_image_url":null,"profile_background_image_url_https":null,"profile_background_tile":false,"profile_image_url":"http:\\/\\/pbs.twimg.com\\/profile_images\\/794559645901852672\\/HxdmM8_j_normal.jpg","profile_image_url_https":"https:\\/\\/pbs.twimg.com\\/profile_images\\/794559645901852672\\/HxdmM8_j_normal.jpg","profile_banner_url":"https:\\/\\/pbs.twimg.com\\/profile_banners\\/4733960663\\/1474214693","profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":true,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"none"},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":794,"favorite_count":202,"favorited":false,"retweeted":false,"lang":"ar"},"is_quote_status":false,"retweet_count":7'
```
which result in the same error message as above.

**Comment by parroty** [comment]
Thanks for the information. It seems the json is partially terminated and causing the error. 

What hashtag is searched for this condition? (I'm checking https://github.com/robinsjdotcom/TrendingHashtagGraph to reproduce, but haven't been able to identify how to use it yet).

> Why not use the decode function instead of decode! from the Poison library?

Not raising a exception could be one option (error handling is one item in the todo list), but it depends on the error condition and how to recover.

Also, I assume wrapping `ExTwitter.search(hashtag, count: 5)` call with try/rescue is one option too.

**Comment by robinsjdotcom** [comment]
```What hashtag is searched for this condition?```
In this case I didn't log the hashtag. However I converted the code points for the value listed under the `:key` and resulted in: ```ا\ل\ش\ب\ا\ب_\ا\ل\ا\ه\ل\ي```. 

The application first searches for trending hashtags using the `ExTwitter.trends/2` function and then it fetches the 5 first tweets with that hashtag. I will reproduce with hashtag and body of the response. 

Yes, the try/resue path is my second option.

**Comment by jann** [comment]
I am getting the same error from time to time. Do you have any news?

**Comment by mazz** [comment]
With Poison 4 I managed to do something similar.
This ExTwitter.Model.Tweet:

```
[debug] response: %ExTwitter.Model.Tweet{created_at: "Sat Sep 22 15:59:31 +0000 2018", text: "@gensep54 @colombia_hist @Santandereanos_ @figuerjoda @CaracolBga @DanArenas @canaltro Así es......que delicia 👌🏼😎", in_reply_to_screen_name: "gensep54", retweet_count: 0, quoted_status_id_str: nil, entities: %{hashtags: [], symbols: [], urls: [], user_mentions: [%{id: 1539649308, id_str: "1539649308", indices: [0, 9], name: "Gabriel Serrano", screen_name: "gensep54"}, %{id: 1216071709, id_str: "1216071709", indices: [10, 24], name: "Historia de Colombia", screen_name: "colombia_hist"}, %{id: 316646685, id_str: "316646685", indices: [25, 41], name: "Santandereanos_", screen_name: "Santandereanos_"}, %{id: 180861689, id_str: "180861689", indices: '*5', name: "JorgeFigueroaClausen", screen_name: "figuerjoda"}, %{id: 2399445835, id_str: "2399445835", indices: '6A', name: "Caracol Bucaramanga", screen_name: "CaracolBga"}, %{id: 66895250, id_str: "66895250", indices: 'BL', name: "Daniel Arenas", screen_name: "DanArenas"}, %{id: 288248471, id_str: "288248471", indices: 'MV', name: "Canal TRO", screen_name: "canaltro"}]}, filter_level: "low", retweeted_status: nil, in_reply_to_status_id_str: "1043523405205708802", in_reply_to_user_id: 1539649308, full_text: nil, display_text_range: 'Wr', extended_tweet: nil, id: 1043530238708408320, quoted_status_id: nil, in_reply_to_user_id_str: "1539649308", withheld_in_countries: nil, possibly_sensitive: nil, truncated: false, extended_entities: nil, withheld_scope: nil, user: %ExTwitter.Model.User{created_at: "Sat Mar 28 21:09:54 +0000 2009", default_profile: false, listed_count: 18, verified: false, utc_offset: nil, profile_use_background_image: true, entities: nil, name: "Carlos E.", profile_background_image_url: "http://abs.twimg.com/images/themes/theme15/bg.png", profile_background_color: "131516", followers_count: 1371, notifications: nil, time_zone: nil, id: 27309081, protected: false, geo_enabled: true, profile_sidebar_border_color: "E2EAEF", location: "ÜT: 4.6770719,-74.0646236", following: nil, withheld_in_countries: nil, profile_image_url_https: "https://pbs.twimg.com/profile_images/572507358519271424/V5OhwMJC_normal.jpeg", url: nil, friends_count: 532, withheld_scope: nil, profile_image_url: "http://pbs.twimg.com/profile_images/572507358519271424/V5OhwMJC_normal.jpeg", description: "Instagram Username: @carlosegs Fotos Derechos Reservados ® YouTube: https://youtu.be/vt9ZI0OOP1Q", profile_sidebar_fill_color: "E2EAEF", screen_name: "carlosegs", ...}, favorited: false, withheld_copyright: nil, retweeted: false, source: "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>", lang: "es", current_user_retweet: nil, geo: nil, scopes: nil, contributors: nil, in_reply_to_status_id: 1043523405205708802, quoted_status: nil, favorite_count: 0, id_str: "1043530238708408320", coordinates: nil, place: %{attributes: %{}, bounding_box: %{coordinates: [[[-73.196439, 7.04893], [-73.196439, 7.240656], [-73.068955, 7.240656], [-73.068955, 7.04893]]], type: "Polygon"}, country: "Colombia", country_code: "CO", full_name: "Bucaramanga, Colombia", id: "015ebf2571d0d8ce", name: "Bucaramanga", place_type: "city", url: "https://api.twitter.com/1.1/geo/id/015ebf2571d0d8ce.json"}}
```

gives me a Poison.ParseError:
```
[error] Error returned, stopping stream ({%Poison.ParseError{pos: 3903, rest: nil, value: "{"}, "{\"created_at\":\"Sat Sep 22 15:59:31 +0000 2018\",\"id\":1043530239584944128,\"id_str\":\"1043530239584944128\",\"text\":\"@JosephStanley82 @susancollins @LindseyGrahamSC Republican, conservative, alt-right people are sending death threat\\u2026 https:\\/\\/t.co\\/SeUmYO2rbY\",\"display_text_range\":[48,140],\"source\":\"\\u003ca href=\\\"http:\\/\\/twitter.com\\\" rel=\\\"nofollow\\\"\\u003eTwitter Web Client\\u003c\\/a\\u003e\",\"truncated\":true,\"in_reply_to_status_id\":1043529103889063937,\"in_reply_to_status_id_str\":\"1043529103889063937\",\"in_reply_to_user_id\":2379182562,\"in_reply_to_user_id_str\":\"2379182562\",\"in_reply_to_screen_name\":\"JosephStanley82\",\"user\":{\"id\":829463993555103745,\"id_str\":\"829463993555103745\",\"name\":\"IndivisibleSC-04\",\"screen_name\":\"IndivisibleSC04\",\"location\":\"Greenville, SC\",\"url\":null,\"description\":\"Indivisible SC District 4 FB:  http:\\/\\/facebook.com\\/indivisiblesc4\\/\",\"translator_type\":\"none\",\"protected\":false,\"verified\":false,\"followers_count\":2789,\"friends_count\":2557,\"listed_count\":47,\"favourites_count\":30708,\"statuses_count\":38163,\"created_at\":\"Wed Feb 08 22:56:41 +0000 2017\",\"utc_offset\":null,\"time_zone\":null,\"geo_enabled\":true,\"lang\":\"en\",\"contributors_enabled\":false,\"is_translator\":false,\"profile_background_color\":\"000000\",\"profile_background_image_url\":\"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\"profile_background_image_url_https\":\"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\"profile_background_tile\":false,\"profile_link_color\":\"1B95E0\",\"profile_sidebar_border_color\":\"000000\",\"profile_sidebar_fill_color\":\"000000\",\"profile_text_color\":\"000000\",\"profile_use_background_image\":false,\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/850079158336184321\\/pCF9k7dm_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/850079158336184321\\/pCF9k7dm_normal.jpg\",\"profile_banner_url\":\"https:\\/\\/pbs.twimg.com\\/profile_banners\\/829463993555103745\\/1491507135\",\"default_profile\":false,\"default_profile_image\":false,\"following\":null,\"follow_request_sent\":null,\"notifications\":null},\"geo\":null,\"coordinates\":null,\"place\":{\"id\":\"8eb7d0abedc4817b\",\"url\":\"https:\\/\\/api.twitter.com\\/1.1\\/geo\\/id\\/8eb7d0abedc4817b.json\",\"place_type\":\"city\",\"name\":\"Greenville\",\"full_name\":\"Greenville, SC\",\"country_code\":\"US\",\"country\":\"United States\",\"bounding_box\":{\"type\":\"Polygon\",\"coordinates\":[[[-82.434848,34.687331],[-82.434848,34.904552],[-82.249689,34.904552],[-82.249689,34.687331]]]},\"attributes\":{}},\"contributors\":null,\"is_quote_status\":false,\"extended_tweet\":{\"full_text\":\"@JosephStanley82 @susancollins @LindseyGrahamSC Republican, conservative, alt-right people are sending death threats to Dr. Ford, Maxine Waters and other Dem legislators.  Don't try to take the high horse because you people are in the gutter.\",\"display_text_range\":[48,242],\"entities\":{\"hashtags\":[],\"urls\":[],\"user_mentions\":[{\"screen_name\":\"JosephStanley82\",\"name\":\"Joseph Stanley\",\"id\":2379182562,\"id_str\":\"2379182562\",\"indices\":[0,16]},{\"screen_name\":\"susancollins\",\"name\":\"Susan Collins\",\"id\":15691917,\"id_str\":\"15691917\",\"indices\":[17,30]},{\"screen_name\":\"LindseyGrahamSC\",\"name\":\"Lindsey Graham\",\"id\":432895323,\"id_str\":\"432895323\",\"indices\":[31,47]}],\"symbols\":[]}},\"quote_count\":0,\"reply_count\":0,\"retweet_count\":0,\"favorite_count\":0,\"entities\":{\"hashtags\":[],\"urls\":[{\"url\":\"https:\\/\\/t.co\\/SeUmYO2rbY\",\"expanded_url\":\"https:\\/\\/twitter.com\\/i\\/web\\/status\\/1043530239584944128\",\"display_url\":\"twitter.com\\/i\\/web\\/status\\/1\\u2026\",\"indices\":[117,140]}],\"user_mentions\":[{\"screen_name\":\"JosephStanley82\",\"name\":\"Joseph Stanley\",\"id\":2379182562,\"id_str\":\"2379182562\",\"indices\":[0,16]},{\"screen_name\":\"susancollins\",\"name\":\"Susan Collins\",\"id\":15691917,\"id_str\":\"15691917\",\"indices\":[17,30]},{\"screen_name\":\"LindseyGrahamSC\",\"name\":\"Lindsey Graham\",\"id\":432895323,\"id_str\":\"432895323\",\"indices\":[31,47]}],\"symbols\":[]},\"favorited\":false,\"retweeted\":false,\"filter_level\":\"low\",\"lang\":\"en\",\"timestamp_ms\":\"1537631971628\"}\r\n{\"created_at\":\"Sat Sep 22 15:59:30 +0000 2018\",\"id\":1043530236154011653,\"id_str\":\"1043530236154011653\",\"text\":\"Busy booth at @e" <> ...}).
```

Not sure where exactly I need to apply a try/rescue..

**Comment by robinsalehjan** [comment]
@mazz I was using the `ExTwitter` library in an `GenServer` so I added the try/rescue code in the function responsible for calling the `ExTwitter` API.

If the parsing failed for some reason, I just rescheduled a request to be sent after 15 minutes and returned the old state of the `GenServer` instead.

The parsing errors are quite arbitrary so you have to workaround it.

**Comment by mazz** [comment]
@robinsalehjan 

Here is what I tried:
```
    stream = 
    try do
      ExTwitter.stream_filter([locations: "-168.8,-57.3,174.4,84.1"], :infinity)
    rescue
      _ -> :error
    end
  
  if stream == :error do
    Logger.debug(":error parsing list")
  else 
    stream
      |> Stream.filter(fn(x) -> x.coordinates != nil || x.place != nil end)
      |> Stream.filter(&has_emoji(&1.text))
      |> Stream.map(fn(x) ->
        coordinates = cond do
          x.coordinates != nil ->
            x.coordinates |> Map.fetch!(:coordinates)
            |> coord_arr_to_str
          x.place != nil ->
            x.place |> get_coordinates_from_place
            |> coord_arr_to_str
          true -> nil
        end
    
        emoji = first_emoji(x.text)
    
        %{emoji: emoji, text: x.text, screen_name: x.user.screen_name,
        profile_image_url: x.user.profile_image_url, coordinates: coordinates}
      end)
  end
```


But `Logger.debug(":error parsing list")` would never be reached. This is also in a GenServer, elixir 1.7.3.

How would you 'reschedule'? New elixir coder here ..

**Comment by robinsalehjan** [comment]
@mazz Heres an example implementation, please ask if anything is unclear.

`defmodule EmojiServer do
    use GenServer

    /// Client API ///

    def start_link() do
        GenServer.start_link(__MODULE__, {:ok, []}, name: EmojiServer) // Register the GenServer
    end

    def init({:ok, state}) do
        send(EmojiServer, :init) // Send an message to ourselves to send the first API request
        {:ok, state} // Immediately reply with the message `{:ok, []}` because we have to wait for the request to return which will update the `GenServer` state.
                    // This is essentially delayed initalization
    end

    def fetch_graph() do
        GenServer.call(EmojiServer, :get, 30_000)
    end

    def handle_call(:get, _from, state) do
        {:reply, state, state}
    end

    // Handle the first API request (The one we sent in the `init` method) - at this point the GenServer state is an empty array.

    def handle_info(:init, state) do
        with {:ok, new_state} <- get_emoji_stream() do
            schedule_api_call(:ok)  // The request succeded - schedule an new one
            {:noreply, new_state} // Replace the current GenServer state (which is an empty array) with the new state.
        else
            {:api_limit, _} ->
                schedule_api_call(:ok) // We have reached the API Limit - Schedule an new request
                {:noreply, state} // Reply with the current state (which is an empty array)

            {:reschedule, _} ->
                schedule_api_call(:reschedule) // The request failed - Schedule to send a request in 5 seconds
                {:noreply, state} // Reply with the current state (which is an empty array)
        end
    end

    // Handle rescheduled requests - at this point the GenServer state should not be empty, and we can reply with the same state if the request fails.

    def handle_info(:update, state) do
        with {:ok, new_state} <- get_emoji_stream() do
            schedule_api_call(:ok) // The request succeded - schedule a new request
            {:noreply, new_state} // Replace the current GenServer state with the new state
        else
            {:api_limit, _} ->
                schedule_api_call(:ok) // We have reached the API Limit - schedule a new request
                {:noreply, state} // Reply with the current state

            {:reschedule, _} ->
                schedule_api_call(:reschedule) // The request failed - Schedule to send a request in 5 seconds
                {:noreply, state} // Reply with the current state
        end
    end

    /// Private API ///

    def get_emoji_stream do
        with {:ok, stream} <- ExTwitter.stream_filter([locations: "-168.8,-57.3,174.4,84.1"], :infinity) do
            emoji_stream =
                stream
                |> Stream.filter(fn(x) -> x.coordinates != nil || x.place != nil end)
                |> Stream.filter(&has_emoji(&1.text))
                |> Stream.map(fn(x) ->

                coordinates = cond do
                    x.coordinates != nil ->
                        x.coordinates
                        |> Map.fetch!(:coordinates)
                        |> coord_arr_to_str
                    x.place != nil ->
                        x.place
                        |> get_coordinates_from_place
                        |> coord_arr_to_str
                    true -> nil

                    emoji = first_emoji(x.text)
                    %{emoji: emoji, text: x.text, screen_name: x.user.screen_name, profile_image_url: x.user.profile_image_url, coordinates: coordinates}
                end)
            {:ok, emoji_stream} // Reply with the new `GenServer` state
        else
            {:error, _} ->
                schedule_api_call(:reschedule) // The request failed - Schedule a new one
        end
    end

    // API request succeeded - send a message to the GenServer with the message :update in 15 minutes

    defp schedule_api_call(:ok) do
        Process.send_after(EmojiServer, :update, 1000 * 60 * 15)
    end

    // API request failed - send a new message to the GenServer with the message :update in 5 seconds

    defp schedule_api_call(:reschedule) do
        Process.send_after(EmojiServer, :update, 5_000)
    end
end
`

**Comment by yatender-oktalk** [comment]
I was also facing same issue with Poison, as far as I searched & debug, the issue was because of Poison rate limit. I started using Tesla in my project, after that it's working fine now I am not using it anymore, you can consider using Tesla if possible. I can send you PR for testing I am sure this issue will not come once you ditch Poison or Potion. FYI potion gives timeout & Poison gives Unexpected end of input once their pool is full.

**Comment by cgorshing** [comment]
I believe this can be closed now that the project has moved to Jason instead of poison. https://github.com/parroty/extwitter/pull/123
