### ISSUE TITLE
Get user's email

### ISSUE THREAD

**Issue by alex88** [parroty/extwitter#68]
On https://github.com/parroty/extwitter/blob/e77527d1b30a26bef357e42cfe84a5d696552667/lib/extwitter.ex#L875 you show that you an actually request an email, I've added that into the apps settings too, however, there is no email in the response of the `verify_credentials` call, is that expect?

**Comment by parroty** [comment]
Thanks for the report, it seems the definition for `verify_credentials` is wrong. 

I'm trying to update the endpoint with above commit. Is it possible for you to try if it works as your expectation? (maybe with following `mix.exs` definition).

```
  defp deps do
    [
      {:extwitter, github: "parroty/extwitter", branch: "fix_68"}
    ]
  end
```

**Comment by alex88** [comment]
It works, thanks!

**Comment by parroty** [comment]
Thanks for the confirmation!
