### ISSUE TITLE
Add support for users/profile_banner

### ISSUE THREAD

**Issue by gmalette** [parroty/extwitter#70]
Hey! Is it possible to add support for [`users/profile_banner`](https://dev.twitter.com/rest/reference/get/users/profile_banner) please?

**Comment by parroty** [comment]
The above is my trial to implement `users/profile_banner`. It would be great if you could try with master branch.

It would be like 
```
def deps do
  [ {:extwitter, github: "parroty/extwitter"} ]
end
```
in the `mix.exs`.

The usage is like the following (as in the tests).
```elixir
test "get profile banners by screen_name" do
  use_cassette "user_profile_banner" do
    profile_banner = ExTwitter.user_profile_banner("twitter")
    assert profile_banner.sizes.web.h > 0
    assert profile_banner.sizes.web.w > 0
  end
end
```

**Comment by gmalette** [comment]
Seems to be working perfectly! Thanks, that was so fast!

**Comment by parroty** [comment]
Thanks, I've pushed as v0.8.2.
