### ISSUE TITLE
Question on how to monitor ExTwitter in a Supervisor

### ISSUE THREAD

**Issue by cheeyeo** [parroty/extwitter#73]
Hi guys,

I'm writing to enquire about suitable architectural decisions one can take with using ExTwitter within a Supervisor in an OTP application?

In a prototype project, I spawn a child task running ExTwitter within a supervisor module.

However, I noticed that ExTwitter would timeout but I'm unable and don't know how to trap these timeout signals to restart the stream again.

Is there a way to do this within a supervisor module, maybe monitoring the pid of the stream or is this an anti-pattern? I've just started building OTP apps and still finding my way around. Thanks for your help in anyway !

**Comment by elitau** [comment]
Have a look at https://github.com/SebastianSzturo/kaisuu
