### ISSUE TITLE
Syntax error when using master branch

### ISSUE THREAD

**Issue by cheeyeo** [parroty/extwitter#75]
The latest change in ```stream_filter/2``` causes a syntax error as follows:

```
== Compilation error on file lib/tweet_streamer/twitter_client.ex ==
** (SyntaxError) lib/tweet_streamer/twitter_client.ex:17: syntax error before: infinity
```
I tried to debug it but can't work out why the typespecs are failing?

**Comment by parroty** [comment]
Thanks for the report,  I think it's related to #74. If your code is as follows, could you try wrapping option values with `[]`? 

```elixir
iex(1)> stream = ExTwitter.stream_filter(track: "apple", :infinity)
** (SyntaxError) iex:1: syntax error before: infinity
```
```elixir
iex(1)> stream = ExTwitter.stream_filter([track: "apple"], :infinity)
#Function<51.48026477/2 in Stream.resource/3>
```

**Comment by parroty** [comment]
I'm closing as above, but if you still have same issue, please reopen or open another one.
