### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by faebser** [parroty/extwitter#76]
I'm currently working on a project where I need to use the streaming APIs of twitter.
I added the dep to mix.exs and the tokens to the config.exs.
Still I am not able to use the API. I also double and triple checked the tokes and also regenerated them
on twitters side.

```elixir
➜ iex -S mix
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ExTwitter.configure()
[consumer_key: "xxx",
 consumer_secret: "xxx",
 access_token: "xxx",
 access_token_secrect: "xxx"]
iex(2)> ExTwitter.search("test")
** (ExTwitter.Error) Could not authenticate you.
    (extwitter) lib/extwitter/api/base.ex:86: ExTwitter.API.Base.parse_error/2
    (extwitter) lib/extwitter/api/search.ex:10: ExTwitter.API.Search.search/2
```

**Comment by parroty** [comment]
I've just retried in my local environment and my keys, but the same command seems working (also, if I intentionally put dummy in one of the parameter (ex. `access_token_secrect`), the error `Could not authenticate you.` becomes displayed.

```elixir
$ ./run_iex.sh
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Enum.count(ExTwitter.search("test"))
14
```

> Still I am not able to use the API. I also double and triple checked the tokes and also regenerated them

I'm still wondering it's related to twitter api permission (as per error message), but it's difficult to isolate as keys are secret. Is it possible to verify the key? (possibly try directly with twitter or other language libraries, etc.).

**Comment by faebser** [comment]
Thanks for your response. I found some strange irregularities. I'm gonna setup asap a github repo to try to isolate a test case for you.

**Comment by faebser** [comment]
I finally found the time to setup for you at https://github.com/faebser/extwitter_test_case.
You can recreate the error by simply running ```iex -S mix``` and then searching for something like ```ExTwitter.search "foo"```.
If you look into the config.exs file you will find two blocks of configuration with comments telling you which one works and vice versa.

Anyway I already have the a nagging feeling that I just overlooked something and you will tell me soon ;)

**Comment by parroty** [comment]
Thanks for the repository creation and sorry being late to respond.  and I could confirm the behavior using the your repository. It seems the difference between `not working` and `working` seems the typo in `access_token_secrect` (is tthis the difference?)
https://github.com/faebser/extwitter_test_case/blob/master/config/config.exs#L38

**Comment by faebser** [comment]
hm, how embarrassing. I was sure that they are the same. Thanks a lot.
