### ISSUE TITLE
Poison version is not up to date

### ISSUE THREAD

**Issue by Virviil** [parroty/extwitter#77]
Poison version gets in conflict with another applications.

This is my output in phoenix umbrella application:

```
Failed to use "poison" (version 3.1.0) because
  /home/virviil/dev/elixir/market_face_umbrella/apps/twsubscriber
/mix.exs requires ~> 3.0
  /home/virviil/dev/elixir/market_face_umbrella/deps/ueberauth_tw
itter/mix.exs requires ~> 1.3 or ~> 2.0 or ~> 3.0 or ~> 4.0
  extwitter (version 0.8.3) requires ~> 2.0
  guardian (version 0.14.4) requires >= 1.3.0
  phoenix (version 1.3.0-rc.2) requires ~> 2.2 or ~> 3.0
  mix.lock specifies 3.1.0

** (Mix) Hex dependency resolution failed, relax the version requ
irements of your dependencies or unlock them (by using mix deps.u
pdate or mix deps.unlock). If you are unable to resolve the confl
icts you can try overriding with {:dependency, "~> 1.0", override
: true}
```

I'm sure, that putting everywhere `override: true` tuple is not the best way to solve this problem.
The same issue [here](https://github.com/ueberauth/ueberauth_twitter/pull/17) - we are still in discussion what to do

**Comment by parroty** [comment]
Thanks for the report, the fix above is pushed. I'm closing at the moment, but if you find remaining issue, please reopen or open another one.
